let codingex=document.querySelector('.nav-bar')
codingex.innerHTML="yo boi its me"
console.log(codingex.innerHTML)
codingex.textContent='yo boi its me 2'
//  let test = document.querySelector('div')
//  let content=document.createElement('p')
//  test.appendChild(content)
//  console.log(test)

// let test = document.querySelector('.div')
// let newpara1=document.createElement('p')
// test.appendChild(newpara1)
// console.log(test)

let example= document.querySelector('.div')
let para=document.createElement('p')
let newpara=document.createTextNode('this is js genreated para')
para.appendChild(newpara)
example.appendChild(para)
console.log(example)
let para1= document.createElement('p')
para1.textContent='this para is generated by the para1'
example.appendChild(para1)
console.log(example)

let newtext=document.createElement('p')
newtext.textContent='this is the para to be added before div of class div'
example.insertAdjacentElement('beforebegin',newtext)
